# Generated by Django 5.0.6 on 2024-06-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=128, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'преимущество',
                'verbose_name_plural': 'преимущества',
            },
        ),
    ]
