# Generated by Django 5.0.6 on 2024-06-30 18:23

import django.db.models.deletion
import sgn2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0002_advantage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('logo', models.ImageField(upload_to=sgn2.models.get_upload_path, verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'компании',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер семестра')),
            ],
            options={
                'verbose_name': 'семестр',
                'verbose_name_plural': 'семестры',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgn2.plan')),
            ],
            options={
                'verbose_name': 'дисциплина',
                'verbose_name_plural': 'дисциплины',
            },
        ),
    ]
