# Generated by Django 5.0.6 on 2024-07-02 08:07

import sgn2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0003_company_plan_discipline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField(unique=True, verbose_name='Баллы за егэ')),
            ],
            options={
                'verbose_name': 'баллы',
                'verbose_name_plural': 'баллы',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.FileField(upload_to=sgn2.models.get_upload_path, verbose_name='Логотип'),
        ),
    ]
