# Generated by Django 5.0.6 on 2024-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0004_statistics_alter_company_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Статистика поступления', 'verbose_name_plural': 'Статистика поступления'},
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='scores',
        ),
        migrations.AddField(
            model_name='statistics',
            name='average_score',
            field=models.IntegerField(null=True, verbose_name='Средний проходной балл'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='budget_places',
            field=models.IntegerField(null=True, verbose_name='Бюджетные места'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='passing_score',
            field=models.IntegerField(null=True, verbose_name='Проходной балл'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='subject1_min_score',
            field=models.IntegerField(null=True, verbose_name='Минимальный балл предмета 1'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='subject1_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Название предмета 1'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='subject2_min_score',
            field=models.IntegerField(null=True, verbose_name='Минимальный балл предмета 2'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='subject2_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Название предмета 2'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='subject3_min_score',
            field=models.IntegerField(null=True, verbose_name='Минимальный балл предмета 3'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='subject3_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Название предмета 3'),
        ),
    ]
