# Generated by Django 5.0.6 on 2024-07-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0005_alter_statistics_options_remove_statistics_scores_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'условия поступления', 'verbose_name_plural': 'условия поступления'},
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='subject1_name',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='subject2_name',
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='subject3_name',
        ),
        migrations.AlterField(
            model_name='statistics',
            name='subject1_min_score',
            field=models.IntegerField(null=True, verbose_name='Минимальный балл по математике'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='subject2_min_score',
            field=models.IntegerField(null=True, verbose_name='Минимальный балл по информатике/истории/математике'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='subject3_min_score',
            field=models.IntegerField(null=True, verbose_name='Минимальный балл по русскому языку'),
        ),
        migrations.CreateModel(
            name='BachelorProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies', models.ManyToManyField(related_name='bachelor_programs', to='sgn2.company')),
                ('semesters', models.ManyToManyField(related_name='bachelor_programs', to='sgn2.plan')),
                ('statistics', models.ManyToManyField(related_name='bachelor_programs', to='sgn2.statistics')),
            ],
            options={
                'verbose_name': 'бакалаврская программа',
                'verbose_name_plural': 'бакалаврские программы',
            },
        ),
        migrations.CreateModel(
            name='MasterProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies', models.ManyToManyField(related_name='master_programs', to='sgn2.company')),
                ('semesters', models.ManyToManyField(related_name='master_programs', to='sgn2.plan')),
                ('statistics', models.ManyToManyField(related_name='master_programs', to='sgn2.statistics')),
            ],
            options={
                'verbose_name': 'магистерская программа',
                'verbose_name_plural': 'магистерские программы',
            },
        ),
    ]
