# Generated by Django 5.0.6 on 2024-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0007_bachelorprogram_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bachelorprogram',
            name='title',
            field=models.CharField(default='Default Title', max_length=128, verbose_name='Название программы'),
        ),
    ]
