# Generated by Django 5.0.6 on 2024-07-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0008_alter_bachelorprogram_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bachelorprogram',
            options={'verbose_name': 'бакалаврская программа', 'verbose_name_plural': 'бакалаврская программа'},
        ),
        migrations.AlterModelOptions(
            name='masterprogram',
            options={'verbose_name': 'магистерская программа', 'verbose_name_plural': 'магистерская программа'},
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='companies',
        ),
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='title',
        ),
        migrations.RemoveField(
            model_name='masterprogram',
            name='companies',
        ),
    ]
