# Generated by Django 5.0.6 on 2024-07-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0009_alter_bachelorprogram_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_score', models.IntegerField(null=True, verbose_name='Проходной балл')),
                ('budget_places', models.IntegerField(null=True, verbose_name='Бюджетные места')),
            ],
            options={
                'verbose_name': 'условия поступления (магистратура)',
                'verbose_name_plural': 'условия поступления (магистратура)',
            },
        ),
        migrations.RenameModel(
            old_name='Statistics',
            new_name='BachelorStatistics',
        ),
        migrations.AlterModelOptions(
            name='bachelorstatistics',
            options={'verbose_name': 'условия поступления (бакалавриат)', 'verbose_name_plural': 'условия поступления (бакалавриат)'},
        ),
        migrations.AlterField(
            model_name='masterprogram',
            name='statistics',
            field=models.ManyToManyField(related_name='master_programs', to='sgn2.masterstatistics'),
        ),
    ]
