# Generated by Django 5.0.6 on 2024-07-02 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0010_masterstatistics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер семестра')),
            ],
            options={
                'verbose_name': 'семестр (магистратура)',
                'verbose_name_plural': 'семестры (магистратура)',
            },
        ),
        migrations.RenameModel(
            old_name='Plan',
            new_name='BachelorPlan',
        ),
        migrations.AlterModelOptions(
            name='bachelorplan',
            options={'verbose_name': 'семестр (бакалавриат)', 'verbose_name_plural': 'семестры (бакалавриат)'},
        ),
        migrations.AlterField(
            model_name='discipline',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgn2.BachelorPlan'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='master_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgn2.MasterPlan'),
        ),
        migrations.AlterField(
            model_name='masterprogram',
            name='semesters',
            field=models.ManyToManyField(related_name='master_programs', to='sgn2.MasterPlan'),
        ),
    ]
