# Generated by Django 5.0.6 on 2024-07-02 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0011_masterplan_rename_plan_bachelorplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sgn2.bachelorplan'),
        ),
    ]
