# Generated by Django 5.0.6 on 2024-07-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0013_alter_discipline_master_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bachelorprogram',
            name='disciplines',
            field=models.ManyToManyField(related_name='bachelor_program_disciplines', to='sgn2.discipline'),
        ),
        migrations.AddField(
            model_name='masterprogram',
            name='disciplines',
            field=models.ManyToManyField(related_name='master_program_disciplines', to='sgn2.discipline'),
        ),
    ]
