# Generated by Django 5.0.6 on 2024-07-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0015_alter_discipline_master_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprogram',
            name='disciplines',
            field=models.ManyToManyField(related_name='master_program_programs', to='sgn2.discipline'),
        ),
    ]
