# Generated by Django 5.0.6 on 2024-07-02 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0016_alter_masterprogram_disciplines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bachelorprogram',
            name='disciplines',
        ),
        migrations.RemoveField(
            model_name='masterprogram',
            name='disciplines',
        ),
    ]
