# Generated by Django 5.0.6 on 2024-07-02 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0017_remove_bachelorprogram_disciplines_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='master_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='sgn2.masterplan'),
        ),
    ]
