# Generated by Django 5.0.6 on 2024-07-02 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0018_alter_discipline_master_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='semester',
        ),
        migrations.AddField(
            model_name='discipline',
            name='bachelor_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disciplines', to='sgn2.bachelorplan'),
        ),
    ]
