# Generated by Django 5.0.6 on 2024-07-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0024_alter_discipline_bachelor_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprogram',
            name='semesters',
        ),
        migrations.RemoveField(
            model_name='masterprogram',
            name='statistics',
        ),
        migrations.AlterModelOptions(
            name='bachelorplan',
            options={'verbose_name': 'Учебный план (бакалавриат)', 'verbose_name_plural': 'Учебные планы (бакалавриат)'},
        ),
        migrations.AlterModelOptions(
            name='masterplan',
            options={'verbose_name': 'Учебный план (магистратура)', 'verbose_name_plural': 'Учебные планы (магистратура)'},
        ),
        migrations.DeleteModel(
            name='BachelorProgram',
        ),
        migrations.DeleteModel(
            name='MasterProgram',
        ),
    ]
