# Generated by Django 5.0.6 on 2024-07-05 20:10

import sgn2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgn2', '0025_remove_masterprogram_semesters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('logo', models.FileField(upload_to=sgn2.models.get_upload_path, verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'компания (магистратура)',
                'verbose_name_plural': 'компании (магистратура)',
            },
        ),
        migrations.RenameModel(
            old_name='Company',
            new_name='BachelorCompany',
        ),
        migrations.AlterModelOptions(
            name='bachelorcompany',
            options={'verbose_name': 'компания (бакалавриат)', 'verbose_name_plural': 'компании (бакалавриат)'},
        ),
    ]
